# -*- coding: utf-8 -*-
"""impostorenda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zJ_kihxMt1UmYnzXFLXyEzqUoLxRXDoW
"""

import time
print("Cálculo do Imposto de Renda")

repetir = True
while repetir:
  print("Digite a opção que enquadra seu salário bruto:")
  #time.sleep(1)
  print("Opção (1) até R$2.112.00")
  #time.sleep(1)
  print("Opção (2) de R$2.112.00 até R$2.826.65")
  #time.sleep(1)
  print("Opção (3) de R$2.826.65 até R$3.751.05")
  #time.sleep(1)
  print("Opção (4) de R$3.751.05 até R$4.664.68")
  #time.sleep(1)
  print("Opção (5) superior a R$4.664.68")
  #time.sleep(1)
  print("****"*8)

  escolha = input("Selecione a opção: ")

  if escolha == "1":
    print("Você é insento do imposto")
  elif escolha == "2":
    salario = input("Digite seu salário: ")
    salario_str = float(salario.replace(".","").replace(",","."))
    parcela = ((salario_str*7.5)/100)
    print(f"Será debitado a parcela de R${parcela:.1f} dos seus ganhos brutos")
  #.....
  elif escolha == "3":
    salario = input("Digite seu salário: ")
    salario_str = float(salario.replace(".","").replace(",","."))
    parcela = ((salario_str*15)/100)
    print(f"Será debitado a parcela de R${parcela:.1f} dos seus ganhos brutos")
  #.....
  elif escolha == "4":
    salario = input("Digite seu salário: ")
    salario_str = float(salario.replace(".","").replace(",","."))
    parcela = ((salario_str*22.5)/100)
    print(f"Será debitado a parcela de R${parcela:.1f} dos seus ganhos brutos")
  #.....
  elif escolha == "5":
    salario = input("Digite seu salário: ")
    salario_str = float(salario.replace(".","").replace(",","."))
    parcela = ((salario_str*27.5)/100)
    print(f"Será debitado a parcela de R${parcela:.1f} dos seus ganhos brutos")
  #.....
  opcao = input("Deseja realizar novamente? S/N\n")
  if opcao.upper( ) != "S":
    repetir = False